### ISSUE TITLE
Update config

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#7108]
### Expected behavior

Application should start and forge by default in devnet/default node mode

```
# System configs can be used both in application and engine
system:
  dataPath: "~/.lisk/default"
  consoleLogLevel: "info". # Merged from logger
  fileLogLevel: "info" # Merged from logger
  keepEventsForHeights: 309

rpc:
  modes:
    - ipc
    - ws
    - http
  host: 0.0.0.0
  port: 7887

genesis:
  # blob as hex encoded block or `fromFile` is required
  block:
    blob: ""
    fromFile: ""
  chainID: "00000000"
  blockTime: 10
  bftBatchSize: 103
  maxTransactionSize: 15360
  minFeePerByte: 1000

network:
  version: '' # Move from network Verion
  port: 7667
  host: 127.0.0.1 # Rename from hostIp
  seedPeers:
    - ip: 127.0.0.1 
      port: 7667
  blacklistedIPs:
  fixedPeers:
  whitelistedPeers:

  maxOutboundConnections:
  maxInboundConnections:
  advertiseAddress:
  wsMaxPayload:
  # Remove below as those are too detail control and not sure if we need to allow those tuning
  # peerBanTime:
  # connectTimeout:
  # sendPeerLimit:
  # maxPeerDiscoveryResponseLength:
  # maxPeerInfoSize:

  # ackTimeout:
  
transactionPool:
  maxTransactions: 4096
  maxTransactionsPerAccount: 64
  transactionExpiryTime: 10800000
  minEntranceFeePriority: "0"
  minReplacementFeeDifference: "10"

generator:
  keys:
    # File format is same format as keys:create, although it is a bit inconsistent since RPC endpoint schema is different 
    fromFile: ""
  
modules:
  auth:
  token:
  dpos:
  reward:
  random:

plugins:
  dashbaord:
```

### Which version(s) does this affect? (Environment, OS, etc...)

development

### Additional Information
Scope is changed due to #7275
